// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: docreader.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ChunkConfig   *ChunkConfig           `protobuf:"bytes,3,opt,name=chunk_config,json=chunkConfig,proto3" json:"chunk_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_docreader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docreader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_docreader_proto_rawDescGZIP(), []int{0}
}

func (x *ParseRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *ParseRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ParseRequest) GetChunkConfig() *ChunkConfig {
	if x != nil {
		return x.ChunkConfig
	}
	return nil
}

type ChunkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkSize     int32                  `protobuf:"varint,1,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	ChunkOverlap  int32                  `protobuf:"varint,2,opt,name=chunk_overlap,json=chunkOverlap,proto3" json:"chunk_overlap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkConfig) Reset() {
	*x = ChunkConfig{}
	mi := &file_docreader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkConfig) ProtoMessage() {}

func (x *ChunkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_docreader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkConfig.ProtoReflect.Descriptor instead.
func (*ChunkConfig) Descriptor() ([]byte, []int) {
	return file_docreader_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkConfig) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *ChunkConfig) GetChunkOverlap() int32 {
	if x != nil {
		return x.ChunkOverlap
	}
	return 0
}

type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X1            float32                `protobuf:"fixed32,1,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            float32                `protobuf:"fixed32,2,opt,name=y1,proto3" json:"y1,omitempty"`
	X2            float32                `protobuf:"fixed32,3,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2            float32                `protobuf:"fixed32,4,opt,name=y2,proto3" json:"y2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_docreader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_docreader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_docreader_proto_rawDescGZIP(), []int{2}
}

func (x *BoundingBox) GetX1() float32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *BoundingBox) GetY1() float32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *BoundingBox) GetX2() float32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *BoundingBox) GetY2() float32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	PageNumber    int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	StartPos      int32                  `protobuf:"varint,4,opt,name=start_pos,json=startPos,proto3" json:"start_pos,omitempty"`
	EndPos        int32                  `protobuf:"varint,5,opt,name=end_pos,json=endPos,proto3" json:"end_pos,omitempty"`
	Bbox          *BoundingBox           `protobuf:"bytes,6,opt,name=bbox,proto3" json:"bbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_docreader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_docreader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_docreader_proto_rawDescGZIP(), []int{3}
}

func (x *Chunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Chunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *Chunk) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *Chunk) GetStartPos() int32 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *Chunk) GetEndPos() int32 {
	if x != nil {
		return x.EndPos
	}
	return 0
}

func (x *Chunk) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

type ParseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*Chunk               `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	TotalPages    int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_docreader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docreader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_docreader_proto_rawDescGZIP(), []int{4}
}

func (x *ParseResponse) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *ParseResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *ParseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_docreader_proto protoreflect.FileDescriptor

const file_docreader_proto_rawDesc = "" +
	"\n" +
	"\x0fdocreader.proto\x12\tdocreader\"\x88\x01\n" +
	"\fParseRequest\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x129\n" +
	"\fchunk_config\x18\x03 \x01(\v2\x16.docreader.ChunkConfigR\vchunkConfig\"Q\n" +
	"\vChunkConfig\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x01 \x01(\x05R\tchunkSize\x12#\n" +
	"\rchunk_overlap\x18\x02 \x01(\x05R\fchunkOverlap\"M\n" +
	"\vBoundingBox\x12\x0e\n" +
	"\x02x1\x18\x01 \x01(\x02R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x02 \x01(\x02R\x02y1\x12\x0e\n" +
	"\x02x2\x18\x03 \x01(\x02R\x02x2\x12\x0e\n" +
	"\x02y2\x18\x04 \x01(\x02R\x02y2\"\xc5\x01\n" +
	"\x05Chunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x1f\n" +
	"\vpage_number\x18\x03 \x01(\x05R\n" +
	"pageNumber\x12\x1b\n" +
	"\tstart_pos\x18\x04 \x01(\x05R\bstartPos\x12\x17\n" +
	"\aend_pos\x18\x05 \x01(\x05R\x06endPos\x12*\n" +
	"\x04bbox\x18\x06 \x01(\v2\x16.docreader.BoundingBoxR\x04bbox\"p\n" +
	"\rParseResponse\x12(\n" +
	"\x06chunks\x18\x01 \x03(\v2\x10.docreader.ChunkR\x06chunks\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2L\n" +
	"\tDocReader\x12?\n" +
	"\bParsePDF\x12\x17.docreader.ParseRequest\x1a\x18.docreader.ParseResponse\"\x00B-Z+github.com/pdf-rag-system/backend/pkg/protob\x06proto3"

var (
	file_docreader_proto_rawDescOnce sync.Once
	file_docreader_proto_rawDescData []byte
)

func file_docreader_proto_rawDescGZIP() []byte {
	file_docreader_proto_rawDescOnce.Do(func() {
		file_docreader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docreader_proto_rawDesc), len(file_docreader_proto_rawDesc)))
	})
	return file_docreader_proto_rawDescData
}

var file_docreader_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_docreader_proto_goTypes = []any{
	(*ParseRequest)(nil),  // 0: docreader.ParseRequest
	(*ChunkConfig)(nil),   // 1: docreader.ChunkConfig
	(*BoundingBox)(nil),   // 2: docreader.BoundingBox
	(*Chunk)(nil),         // 3: docreader.Chunk
	(*ParseResponse)(nil), // 4: docreader.ParseResponse
}
var file_docreader_proto_depIdxs = []int32{
	1, // 0: docreader.ParseRequest.chunk_config:type_name -> docreader.ChunkConfig
	2, // 1: docreader.Chunk.bbox:type_name -> docreader.BoundingBox
	3, // 2: docreader.ParseResponse.chunks:type_name -> docreader.Chunk
	0, // 3: docreader.DocReader.ParsePDF:input_type -> docreader.ParseRequest
	4, // 4: docreader.DocReader.ParsePDF:output_type -> docreader.ParseResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_docreader_proto_init() }
func file_docreader_proto_init() {
	if File_docreader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docreader_proto_rawDesc), len(file_docreader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docreader_proto_goTypes,
		DependencyIndexes: file_docreader_proto_depIdxs,
		MessageInfos:      file_docreader_proto_msgTypes,
	}.Build()
	File_docreader_proto = out.File
	file_docreader_proto_goTypes = nil
	file_docreader_proto_depIdxs = nil
}
